### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by ghost** [jgarzik/moxiebox#19]
There seems to be some inconsistencies in the coding style throughout the project.

What is the authoritative style?

To be more specific, on bracket placement:

```
if (expr) {

}
```

Or

```
if (expr)
  {

  }
```

Or this:

```
if (expr)
{

}
```

And what is the tab vs spaces preference? It seems like tabs and spaces are used interchangeably for indentation.

**Comment by jgarzik** [comment]
1. The first example is preferred...
```
if (expr) {
} else {
}
```
2. prefer tab.  sometimes editors mangle.

**Comment by ghost** [comment]
Issues tend to accumulate, but thank you for getting around to this one! I think I brought this up for a indentation patch, but now I'm not sure if I'll get around to it. Thanks for the response though!
